# Status
AUTHENTICATED = 'AUTHENTICATED'
BLOCKED = 'BLOCKED'
ERROR = 'ERROR'
FAIL = 'FAIL'
SUCCESS = 'SUCCESS'

# Configs
SESSION_TIMEOUT = 1800  # 30 minutes
OTP_LENGTH = 6
MAX_ATTEMPTS = 3
MAX_RESENDS = 3
MAX_LOGIN_ATTEMPTS = 3
