OUT_OF_ALERTS_MSG = 'You\'re out of alerts!\n\n'
LOW_ALERTS_WARNING_MSG = '{units_left} alert(s) left!\n\n'
STANDARD_ALERT_MSG = '(www.smsalertservice.com)\n\nr/{subreddit}: {keywords}\n\n{url}'
OTP_MSG = 'Your SMS Alert Service verification code is {otp}.'
ORDER_CONFIRMATION_MSG = '{order_description} have been added to your account! Thank you for using the SMS Alert Service.'
